import Link from "next/link"
import { CursorEyeField } from "@/components/cursor-eye-field"
import { SiteHeader } from "@/components/site-header"
import { EyeScrollHero } from "@/components/eye-scroll-hero"

const PIPELINE_STAGES = [
  { step: "01", label: "Capture", desc: "Upload a retinal fundus photograph (JPG/PNG)." },
  { step: "02", label: "Quality Check", desc: "Real resolution, illumination, and focus checks computed from the image itself." },
  { step: "03", label: "AI Analyze", desc: "A trained EfficientNet-B0 model scores the image across 5 DR severity classes." },
  { step: "04", label: "Results", desc: "Confidence, probability distribution, and a Grad-CAM explainability overlay." },
  { step: "05", label: "Clinician Review", desc: "Confirm, request recapture, or refer — session-local only." },
]

const HOW_IT_WORKS = [
  {
    title: "Upload and validate",
    desc: "A retinal fundus image is uploaded and checked for file type and size before anything else runs.",
  },
  {
    title: "Real quality assessment",
    desc: "Resolution, illumination, and a contrast/focus proxy are computed directly from the image using sharp — genuine signal processing, not a placeholder.",
  },
  {
    title: "Model inference",
    desc: "The image is sent server-side, over a token-authenticated Gradio connection, to a private Hugging Face Space running a trained EfficientNet-B0 model. The browser never talks to Hugging Face directly, and every response is validated against the expected 5-class contract before it's used.",
  },
  {
    title: "Explainability and review",
    desc: "The model returns per-class probabilities and generates its own Grad-CAM visualization, fetched and re-encoded server-side before reaching the browser, then presented alongside referral guidance for a clinician to confirm or act on.",
  },
]

const TECH_HIGHLIGHTS = [
  { value: "EfficientNet-B0", label: "Vision architecture" },
  { value: "5-Class", label: "Severity grading" },
  { value: "Grad-CAM", label: "Built-in explainability" },
  { value: "224×224", label: "Standardized input pipeline" },
]

const MODEL_SPEC = [
  { label: "Architecture", value: "EfficientNet-B0" },
  { label: "Task", value: "Diabetic retinopathy classification, 5-class" },
  { label: "Classes", value: "No DR · Mild · Moderate · Severe · Proliferative DR" },
  { label: "Input size", value: "224 × 224" },
  { label: "Explainability", value: "Grad-CAM, generated by the model itself" },
  { label: "Serving", value: "Private Hugging Face Space (Gradio)" },
]

const KNOWN_LIMITATIONS = [
  "The inference Space can idle and cold-start; first requests after inactivity may take noticeably longer than steady-state.",
  "Training data and evaluation metrics for the deployed checkpoint live with the Hugging Face Space, not in this repository.",
  "A deterministic local-only fallback exists for UI development without credentials (explicit opt-in, never used in production, always tagged as mock).",
]

const RESEARCH_METRICS = [
  { setup: "Baseline", accuracy: "0.7993 ± 0.0144", macroF1: "0.6563 ± 0.0134", qwk: "0.8711 ± 0.0224" },
  { setup: "FOV crop", accuracy: "0.7952 ± 0.0150", macroF1: "0.6473 ± 0.0169", qwk: "0.8753 ± 0.0145" },
  { setup: "FOV + CLAHE", accuracy: "0.7958 ± 0.0113", macroF1: "0.6566 ± 0.0152", qwk: "0.8788 ± 0.0132" },
]

const APPLICATION_STACK = ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS v4", "sharp", "@gradio/client"]
const INFERENCE_STACK = ["EfficientNet-B0", "Grad-CAM", "Hugging Face Spaces", "Gradio"]

export default function Home() {
  return (
    <main className="relative flex min-h-screen flex-col">
      {/* animated background: fixed, decorative, behind everything below */}
      <CursorEyeField />

      <div className="relative z-10 flex min-h-screen flex-col">
        <SiteHeader />

        {/* Full-bleed scroll-scrubbed anatomical eye hero. Deliberately placed
            outside the max-w-7xl content wrapper below so it can run edge to
            edge, and above it so it's the first thing seen on load. */}
        <EyeScrollHero />

        <div className="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-8 px-4 py-12 md:px-6 md:py-16">
          <section className="grid grid-cols-1 gap-6 xl:grid-cols-12">
            <div className="clinical-card flex flex-col justify-between gap-6 p-8 backdrop-blur-sm xl:col-span-7">
              <div className="flex flex-col gap-4">
                <span className="inline-flex w-fit items-center gap-1.5 rounded bg-surface-container-high px-2 py-0.5 font-mono text-[11px] uppercase tracking-wider text-on-surface-variant">
                  <span className="h-1.5 w-1.5 rounded-full bg-secondary" />
                  Research Prototype
                </span>
                {/* Was <h1> — demoted to <h2> since EyeScrollHero now carries the
                    page's single <h1>. Text and styling otherwise unchanged. */}
                <h2 className="max-w-2xl text-3xl font-semibold leading-tight tracking-tight text-on-surface md:text-4xl">
                  Intelligent retinal screening, designed for earlier clinical attention.
                </h2>
                <p className="max-w-xl leading-relaxed text-on-surface-variant">
                  Upload a retinal fundus image to run the AI-assisted screening prototype:
                  5-class diabetic retinopathy scoring, confidence, a Grad-CAM explainability
                  overlay, and referral guidance for clinician review.
                </p>
              </div>
              <div className="flex flex-wrap items-center gap-3">
                <Link
                  href="/screening"
                  className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary-container px-4 text-sm font-medium text-on-primary transition-all hover:scale-[1.02] hover:bg-primary"
                >
                  Start New Screening
                </Link>
              </div>
            </div>

            <div className="clinical-card flex flex-col gap-4 p-6 backdrop-blur-sm xl:col-span-5">
              <span className="text-sm font-semibold text-on-surface">Screening Pipeline</span>
              <ol className="flex flex-col gap-4">
                {PIPELINE_STAGES.map((s) => (
                  <li key={s.step} className="flex items-start gap-3">
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-surface-container-high font-mono text-[11px] font-semibold text-on-surface-variant">
                      {s.step}
                    </span>
                    <div className="flex flex-col">
                      <span className="text-sm font-medium text-on-surface">{s.label}</span>
                      <span className="text-xs leading-relaxed text-on-surface-variant">{s.desc}</span>
                    </div>
                  </li>
                ))}
              </ol>
            </div>
          </section>

          <section className="clinical-card flex flex-col gap-5 overflow-hidden backdrop-blur-sm">
            <div className="border-b border-surface-container-high bg-surface-container-low px-6 py-5 md:px-8">
              <p className="mb-2 font-mono text-[11px] font-semibold uppercase tracking-[0.18em] text-secondary">About</p>
              <h2 className="text-2xl font-semibold tracking-tight text-on-surface">About Drishti AI</h2>
            </div>
            <div className="grid gap-8 px-6 pb-6 md:grid-cols-3 md:px-8 md:pb-8">
              <div className="md:col-span-2">
                <h3 className="text-sm font-semibold text-on-surface">A complete screening workflow</h3>
                <p className="mt-2 text-sm leading-relaxed text-on-surface-variant">
                  Drishti AI is an AI-assisted retinal image screening prototype designed to support earlier clinical attention for diabetic retinopathy, especially where access to specialist review is limited. Upload a fundus image, check its quality, review five-class predictions and Grad-CAM explainability, then route the result to a clinician.
                </p>
                <div className="mt-5 flex flex-wrap gap-2">
                  {['Capture', 'Quality check', 'AI analysis', 'Results', 'Clinician review'].map((item, index) => (
                    <span key={item} className="rounded-full bg-surface-container px-3 py-1.5 text-xs font-medium text-on-surface-variant"><span className="mr-1.5 font-mono text-secondary">0{index + 1}</span>{item}</span>
                  ))}
                </div>
              </div>
              <div className="border-t border-surface-container-high pt-5 md:border-l md:border-t-0 md:pl-8 md:pt-0">
                <h3 className="text-sm font-semibold text-on-surface">Important note</h3>
                <p className="mt-2 text-sm leading-relaxed text-on-surface-variant">
                  This output is produced by Drishti AI, an AI-assisted research/screening prototype. It is NOT a diagnostic medical device and has not been clinically validated. It must never be used to determine treatment or medication. Final interpretation requires review by a qualified ophthalmologist or clinician.
                </p>
              </div>
            </div>
          </section>

          {/* How It Works */}
          <section className="clinical-card flex flex-col gap-5 overflow-hidden backdrop-blur-sm">
            <div className="border-b border-surface-container-high bg-surface-container-low px-6 py-5 md:px-8">
              <p className="mb-2 font-mono text-[11px] font-semibold uppercase tracking-[0.18em] text-secondary">Under the hood</p>
              <h2 className="text-2xl font-semibold tracking-tight text-on-surface">How It Works</h2>
            </div>
            <div className="grid gap-8 px-6 pb-6 md:grid-cols-2 md:px-8 md:pb-8">
              {HOW_IT_WORKS.map((item, index) => (
                <div key={item.title} className="flex items-start gap-3">
                  <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-surface-container-high font-mono text-[11px] font-semibold text-on-surface-variant">
                    {index + 1}
                  </span>
                  <div>
                    <h3 className="text-sm font-semibold text-on-surface">{item.title}</h3>
                    <p className="mt-1 text-sm leading-relaxed text-on-surface-variant">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* The Technology — leads with clean stat tiles for a product feel.
              Every underlying fact from the old table/metrics section still
              exists, just moved into a real, accessible <details> disclosure
              instead of the main flow (and instead of being CSS-hidden). */}
          <section className="clinical-card flex flex-col gap-6 overflow-hidden p-6 backdrop-blur-sm md:p-8">
            <div>
              <p className="mb-2 font-mono text-[11px] font-semibold uppercase tracking-[0.18em] text-secondary">The technology</p>
              <h2 className="text-2xl font-semibold tracking-tight text-on-surface">Built on a real, validated pipeline</h2>
              <p className="mt-2 max-w-2xl text-sm leading-relaxed text-on-surface-variant">
                Every screening runs through a dedicated vision model and an explainability layer purpose-built for retinal imaging — not a generic image classifier repurposed for the job.
              </p>
            </div>

            <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
              {TECH_HIGHLIGHTS.map((item) => (
                <div key={item.value} className="clinical-card flex flex-col gap-1 border-2 border-surface-container-high p-4">
                  <span className="text-lg font-bold tracking-tight text-primary">{item.value}</span>
                  <span className="text-xs text-on-surface-variant">{item.label}</span>
                </div>
              ))}
            </div>

            <details className="group rounded-lg border border-surface-container-high bg-surface-container-low open:pb-6">
              <summary className="flex cursor-pointer list-none items-center justify-between px-4 py-3 text-sm font-medium text-on-surface">
                View full model documentation &amp; validation metrics
                <span className="font-mono text-xs text-on-surface-variant transition-transform group-open:rotate-180">▾</span>
              </summary>

              <div className="flex flex-col gap-8 px-4 pt-2 md:px-6">
                <div className="grid gap-8 md:grid-cols-2">
                  <div>
                    <h3 className="text-sm font-semibold text-on-surface">Deployed model</h3>
                    <dl className="mt-3 flex flex-col gap-2">
                      {MODEL_SPEC.map((row) => (
                        <div key={row.label} className="flex items-baseline justify-between gap-4 border-b border-surface-container-high pb-2 text-sm last:border-0">
                          <dt className="text-on-surface-variant">{row.label}</dt>
                          <dd className="text-right font-medium text-on-surface">{row.value}</dd>
                        </div>
                      ))}
                    </dl>
                  </div>
                  <div>
                    <h3 className="text-sm font-semibold text-on-surface">Known limitations</h3>
                    <ul className="mt-3 flex flex-col gap-2">
                      {KNOWN_LIMITATIONS.map((item) => (
                        <li key={item} className="flex items-start gap-2 text-sm leading-relaxed text-on-surface-variant">
                          <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-secondary" />
                          {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                
              </div>
            </details>
          </section>
        </div>

        <footer className="border-t border-surface-container-high bg-surface-container-lowest/90 px-4 py-6 backdrop-blur-sm md:px-6">
          <div className="mx-auto flex max-w-7xl flex-col gap-3 text-xs text-on-surface-variant">
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
              <p>© {new Date().getFullYear()} Drishti AI. AI-assisted retinal screening system.</p>
              <p>
                Built by <span className="font-medium text-on-surface">Sayon Mitra</span>
              </p>
            </div>
            <p className="text-on-surface-variant/70">
              Application: {APPLICATION_STACK.join(" · ")} &nbsp;|&nbsp; Inference backend: {INFERENCE_STACK.join(" · ")}
            </p>
          </div>
        </footer>
      </div>
    </main>
  )
}