"use client"

import { useState } from "react"
import type { ExplainabilityResult } from "@/lib/types"

export function GradcamViewer({
  imageUrl,
  explainability,
}: {
  imageUrl: string
  explainability: ExplainabilityResult
}) {
  const [mode, setMode] = useState<"original" | "gradcam">("original")

  return (
    <div className="clinical-card overflow-hidden">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-surface-container-high bg-surface-container-low p-2">
        <div className="inline-flex rounded-lg bg-surface-container p-0.5">
          <button
            type="button"
            onClick={() => setMode("original")}
            className={`rounded-md px-3 py-1.5 text-xs font-medium transition-all ${
              mode === "original" ? "bg-surface-container-lowest text-primary shadow-sm" : "text-on-surface-variant"
            }`}
          >
            Original Fundus
          </button>
          <button
            type="button"
            disabled={!explainability.available}
            onClick={() => setMode("gradcam")}
            className={`rounded-md px-3 py-1.5 text-xs font-medium transition-all disabled:opacity-40 ${
              mode === "gradcam" ? "bg-surface-container-lowest text-primary shadow-sm" : "text-on-surface-variant"
            }`}
          >
            Explainability Overlay
          </button>
        </div>
        {explainability.type === "illustrative_mock" && mode === "gradcam" && (
          <span className="rounded bg-secondary-fixed px-2 py-0.5 font-mono text-[10px] font-bold uppercase text-on-secondary-fixed">
            Illustrative Mock — Not a Trained Model
          </span>
        )}
        {explainability.type === "trained_model" && mode === "gradcam" && (
          <span className="rounded bg-secondary-fixed px-2 py-0.5 font-mono text-[10px] font-bold uppercase text-on-secondary-fixed">
            Model-Generated — Not Clinically Validated
          </span>
        )}
      </div>

      <div className="relative aspect-square w-full overflow-hidden bg-[#0a0708]">
        {mode === "original" && (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={imageUrl} alt="Uploaded retinal fundus image" className="h-full w-full object-contain" />
        )}

        {mode === "gradcam" && explainability.available && explainability.type === "trained_model" && explainability.gradcam && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={explainability.gradcam}
            alt="Grad-CAM explainability overlay generated by the model"
            className="h-full w-full object-contain"
          />
        )}

        {mode === "gradcam" && explainability.available && explainability.type === "illustrative_mock" && (
          <>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={imageUrl} alt="Uploaded retinal fundus image" className="h-full w-full object-contain" />
            {explainability.hotspots && (
              <svg viewBox="0 0 100 100" className="absolute inset-0 h-full w-full" style={{ mixBlendMode: "screen" }}>
                <defs>
                  {explainability.hotspots.map((h, i) => (
                    <radialGradient key={i} id={`hotspot-${i}`} cx="50%" cy="50%" r="50%">
                      <stop offset="0%" stopColor="#8B1E2D" stopOpacity={0.9} />
                      <stop offset="45%" stopColor="#FF9D2E" stopOpacity={0.6} />
                      <stop offset="100%" stopColor="#093263" stopOpacity={0} />
                    </radialGradient>
                  ))}
                </defs>
                {explainability.hotspots.map((h, i) => (
                  <circle key={i} cx={h.cx} cy={h.cy} r={h.r} fill={`url(#hotspot-${i})`} />
                ))}
              </svg>
            )}
          </>
        )}

        {mode === "gradcam" && !explainability.available && (
          <div className="absolute inset-0 flex items-center justify-center bg-inverse-surface/70 p-4 text-center text-sm text-inverse-on-surface">
            {explainability.notice}
          </div>
        )}
      </div>

      <p className="border-t border-surface-container-high bg-surface-container-low p-2 font-mono text-[11px] text-on-surface-variant">
        {explainability.notice}
      </p>
    </div>
  )
}
