import { createHash } from "node:crypto"
import { DR_CLASSES, type DRClassName, type ExplainabilityResult, type Probabilities } from "./types"

/**
 * ============================================================================
 * MOCK_MODE=true — LOCAL-DEV-ONLY FALLBACK HEURISTIC (not used by default)
 * ============================================================================
 *
 * As of the Hugging Face backend integration, the real model
 * (EfficientNet-B0, served privately at sayon-mitra024/drishti-ai-inference)
 * is the default and primary inference path — see lib/hf-inference.ts and
 * app/api/predict/route.ts.
 *
 * This module is kept ONLY as an explicit opt-in fallback (MOCK_MODE=true)
 * for local UI development when HF_TOKEN is not configured or the developer
 * wants to exercise the workflow without calling the real backend. It
 * produces DETERMINISTIC, IMAGE-DERIVED but NOT ML-DERIVED probabilities.
 * It must never be presented as a real diagnostic result, and every response
 * that flows through this module is tagged `model.mock = true` with a
 * persistent "Prototype / Mock Inference" UI notice.
 * ============================================================================
 */

export const MOCK_MODEL_INFO = {
  architecture: "MOCK_HEURISTIC (no trained checkpoint present in repository)",
  version: "prototype-0.1.0",
  mock: true,
} as const

function seededRandom(seed: number) {
  let state = seed % 2147483647
  if (state <= 0) state += 2147483646
  return () => {
    state = (state * 16807) % 2147483647
    return (state - 1) / 2147483646
  }
}

function bufferSeed(buffer: Buffer): number {
  const hash = createHash("sha256").update(buffer).digest()
  return hash.readUInt32BE(0)
}

/**
 * Derives 5 class probabilities deterministically from image bytes.
 * This is NOT a trained classifier — it is a seeded distribution generator
 * used purely to exercise the UI/API contract deterministically per image.
 */
export function runMockInference(imageBuffer: Buffer): {
  classId: number
  className: DRClassName
  confidence: number
  probabilities: Probabilities
} {
  const seed = bufferSeed(imageBuffer)
  const rand = seededRandom(seed)

  const rawWeights = DR_CLASSES.map(() => Math.pow(rand(), 2.2) + 0.02)
  const sum = rawWeights.reduce((a, b) => a + b, 0)
  const normalized = rawWeights.map((w) => w / sum)

  let maxIdx = 0
  for (let i = 1; i < normalized.length; i++) {
    if (normalized[i] > normalized[maxIdx]) maxIdx = i
  }

  const probabilities = DR_CLASSES.reduce((acc, name, i) => {
    acc[name] = Math.round(normalized[i] * 10000) / 10000
    return acc
  }, {} as Probabilities)

  return {
    classId: maxIdx,
    className: DR_CLASSES[maxIdx],
    confidence: probabilities[DR_CLASSES[maxIdx]],
    probabilities,
  }
}

/**
 * Generates an illustrative-only explainability overlay. There is no real
 * Grad-CAM implementation in this repository to reuse, so this produces
 * deterministic hotspot coordinates for a purely visual mock overlay.
 * Clearly marked `type: "illustrative_mock"` end to end.
 */
export function runMockExplainability(imageBuffer: Buffer, classId: number): ExplainabilityResult {
  if (classId === 0) {
    return {
      available: false,
      type: "unavailable",
      notice:
        "No explainability overlay generated for 'No DR' predictions in this prototype heuristic.",
    }
  }

  const seed = bufferSeed(imageBuffer) ^ 0x9e3779b9
  const rand = seededRandom(seed)
  const hotspotCount = 1 + Math.min(2, classId)

  const hotspots = Array.from({ length: hotspotCount }, () => ({
    cx: 30 + rand() * 40,
    cy: 30 + rand() * 40,
    r: 12 + rand() * 10 + classId * 2,
    weight: Math.round((0.4 + rand() * 0.5) * 100) / 100,
  }))

  return {
    available: true,
    type: "illustrative_mock",
    notice:
      "Prototype explainability overlay — illustrative placeholder only. Not generated by a trained Grad-CAM model. See MODEL_CARD.md.",
    hotspots,
  }
}
